# Generated by Django 5.1.5 on 2025-01-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_short_url_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_url',
            name='short',
        ),
    ]
