# Generated by Django 5.1.5 on 2025-01-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_remove_short_url_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_url',
            name='short',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='original',
            field=models.URLField(unique=True),
        ),
    ]
